// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgA1SRrU7uJvjtKYVK59QxQoyH-EWwvJo',
    appId: '1:277725000121:web:7fd0daf592796ad9f54668',
    messagingSenderId: '277725000121',
    projectId: 'amos-project-1-b1fa2',
    authDomain: 'amos-project-1-b1fa2.firebaseapp.com',
    storageBucket: 'amos-project-1-b1fa2.appspot.com',
    measurementId: 'G-S9HSQERDEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPygqAau-CZDQAQCWLGDiMimMgOt33Gm4',
    appId: '1:277725000121:android:51663cbb79840184f54668',
    messagingSenderId: '277725000121',
    projectId: 'amos-project-1-b1fa2',
    storageBucket: 'amos-project-1-b1fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSbANBKwJSj7v9ESUHD_-8OSznPjL8JGw',
    appId: '1:277725000121:ios:b98370de83dc2d22f54668',
    messagingSenderId: '277725000121',
    projectId: 'amos-project-1-b1fa2',
    storageBucket: 'amos-project-1-b1fa2.appspot.com',
    iosBundleId: 'com.amos.projectApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSbANBKwJSj7v9ESUHD_-8OSznPjL8JGw',
    appId: '1:277725000121:ios:5a6930046cd1b11ef54668',
    messagingSenderId: '277725000121',
    projectId: 'amos-project-1-b1fa2',
    storageBucket: 'amos-project-1-b1fa2.appspot.com',
    iosBundleId: 'com.amos.projectApp1.RunnerTests',
  );
}
